### ISSUE TITLE
Async Class

### ISSUE THREAD

**Issue by holymode** [yoou3-cyber/prodiapy#2]
Why is there an async class when its using request and not aiohttp? 
There is no point, because request is still blocking.

**Comment by holymode** [comment]
Png info should also return a dict instead of raw text. 

if validate_denoise(denoising_strength) returns wrong error message -> CFG scale instead of DN

**Comment by zenafey** [comment]
Thanks for info, will be fixed 😎

**Comment by holymode** [comment]
Might be also good to return the payload dict in prodia_response class. 
Could be useful for discord bots. 

Reducing the sleep time between each status check would also better, since 2s is quite high.

**Comment by zenafey** [comment]
3.4 update released
