### ISSUE TITLE
SD / SDXL

### ISSUE THREAD

**Issue by raymerjacque** [yoou3-cyber/prodiapy#3]
I see the endpoint for both the regular models as well as the SDXL use the same Endpoint, its the urls that differ and very minor as well. example :

regular endpoint :  https://api.prodia.com/v1/sd/generate

SDXL endpoint : https://api.prodia.com/v1/sdxl/generate

my question is, why have you guys not updated this github to add the sdxl model ?

**Comment by zenafey** [comment]
3.6 update
