### ISSUE TITLE
Request for Compatibility with Lower Python Versions

### ISSUE THREAD

**Issue by NowLoadY** [yoou3-cyber/prodiapy#4]
Dear ProdiaPy Developers,

I am currently using your ProdiaPy library for a project, and I find it very useful. However, I am encountering a problem due to my Python environment. I am using Python version lower than 3.10 (3.8.17), and it seems that your library uses the `match` statement, which is a feature introduced in Python 3.10.

Unfortunately, upgrading my Python version is not an option for me at the moment due to various reasons. I was wondering if it would be possible for you to provide a version of ProdiaPy that is compatible with lower Python versions, or if there is a workaround that you could suggest.

I understand that this might require additional work, but it would be greatly appreciated. Thank you for your time and consideration.

Best Regards,
NowLoadY

**Comment by zenafey** [comment]
Hello! Thank you for reporting this issue! I will try to create prodiapy version for lower Python

**Comment by Hickory420** [comment]
@NowLoadY , just out of curiosity, what version of python are you limited to?

**Comment by NowLoadY** [comment]
> @NowLoadY , just out of curiosity, what version of python are you limited to?

Hey, Hickory420! I'm currently working with Python 3.8.17 and can't easily bump it up for now.

**Comment by NowLoadY** [comment]
> zenafey

Thank you so much for looking into this! I'm really hoping there might be a way to make ProdiaPy compatible with older Python versions. Your help would mean a lot!

**Comment by zenafey** [comment]
Uploaded to Pypi alpha ver of prodiapy with support of 3.8, you can install it using this command:
```
python -m pip install prodiapy==5.0a1
```
please report any issues you got using it, thanks

**Comment by NowLoadY** [comment]
> Uploaded to Pypi alpha ver of prodiapy with support of 3.8, you can install it using this command:
> 
> ```
> python -m pip install prodiapy==5.0a1
> ```
> 
> please report any issues you got using it, thanks

sure, no problem. thanks!
