### ISSUE TITLE
Does Python 3.8.6 also not work?

### ISSUE THREAD

**Issue by kerafb** [yoou3-cyber/prodiapy#5]
I am using Python version 3.8.6. Why is this library not working?

**Comment by zenafey** [comment]
The minimal python requirement is 3.11 bcos of match/case usage in code, development of lib version for lower python is on roadmap

**Comment by kerafb** [comment]
Thanks & Regards

**Comment by zenafey** [comment]
Uploaded to Pypi alpha ver of prodiapy with support of 3.8, you can install it using this command:
```
python -m pip install prodiapy==5.0a1
```
please report any issues you got using it, thanks
