### ISSUE TITLE
The current library creates images in small sizes.

### ISSUE THREAD

**Issue by kerafb** [yoou3-cyber/prodiapy#6]
This code used to work but now it doesn't.
Small size images are downloaded with the current library code.
In the code I gave, 1024x1024 images could previously be downloaded.
How can I solve this problem?

`from prodiapy import StableDiffusionXL`

`def resimcek(prodia_apikey, sorgu):
    while True:
        try:
            pipe = StableDiffusionXL(
                api_key=prodia_apikey
            )
            job = pipe.generate(prompt=sorgu)
            result = pipe.wait_for(job)
            image = result['imageUrl']
            image1 = image.startswith("https://") 
            if bool(image) and bool(image1):
                return image
            else:
                print("Resim Çekilemedi. 5 Saniye Sonra Tekrar Denenecek")
                sleep(5)
        except Exception as e20:
            print("Prodia Hata Alındı. Tekrar Denenecek. Hata Kodu e20: "+str(e20))
            yaz = open("log.txt", "a", encoding="utf-8")
            yaz.write("Prodia Hata Alındı. Tekrar Denenecek. Hata Kodu e20: "+str(e20)+"\n")
            yaz.close()
            sleep(5)`

**Comment by zenafey** [comment]
This version of prodiapy is deprecated, install 4.6+
